export const allFieldLabels = {
  FirstName: 'First Name',
  LastName: 'Last Name',
  Salutation: 'Title',
  BrokerRating: 'Broker Rating',
  street: 'Street',
  suite: 'Suite',
  City: 'City',
  ProvState: 'Province/State',
  ZipPostal: 'Postal',
  Phone: 'Phone',
  CommPhone: 'Phone',
  mobile: 'Mobile',
  Fax: 'Fax',
  webSiteURL: 'Website',
  MLSNo: 'MLS No.',
  RECONumber: 'Reco Number',
  Notes: 'Notes',
  Address1: 'Address1',
  Address2: 'Address2',
  Country: 'Country',
  Email: 'Email',
  CommEmail: 'Email',
  employer: 'Employer',
  occupation: 'Occupation',
  age: 'Age',
  gender: 'Gender',
  martialStatus: 'Marital Status',
  ethnicity: 'Ethnicity',
  ContactName: 'Contact Name',
  brokerageName: 'Brokerage Name',
  agency: 'Broker Agency',
  designation: 'Designation',
  category: 'Category',
  LegalFullName: 'Company Name',
  IsCompany: 'Corp?',
  portalAccess: 'Portal Access',
  blocked: 'Locked',
  Active: 'Active',
  license: 'Document',
  HomePhone: 'Home Phone',
  WorkPhone: 'Work Phone',
  WorkEmail: 'Work Email',
  Employer: 'Employer',
  Occupation: 'Occupation',
  WebSiteURL: 'Web Site URL',
};

export const roleFields = {
  brokers: [
    { key: 'FirstName', size: '', hideInList: true },
    { key: 'LastName', size: '', hideInList: true },
    { key: 'agency', size: 24, hideInList: true },
    { key: 'Email', size: '', hideInList: true },
    { key: 'WebSiteURL', size: '' },
    { key: 'Notes', size: '' },
  ],
  client: [
    { key: 'Address1', size: 12, parentKey: 'BuyerClient_id' },
    { key: 'Address2', size: 12, parentKey: 'BuyerClient_id' },
    { key: 'City', size: 7, parentKey: 'BuyerClient_id' },
    { key: 'ProvState', size: 5, parentKey: 'BuyerClient_id' },
    { key: 'ZipPostal', size: 4, parentKey: 'BuyerClient_id' },
    { key: 'Country', size: 8, parentKey: 'BuyerClient_id' },
    { key: 'ContactName', size: 4, parentKey: 'BuyerClient_id' },
    { key: 'CommPhone', size: '', parentKey: 'BuyerClient_id' },
    { key: 'CommEmail', size: '', parentKey: 'BuyerClient_id' },
    { key: 'HomePhone', size: '', parentKey: 'BuyerClient_id' },
    { key: 'WorkPhone', size: '', parentKey: 'BuyerClient_id' },
    { key: 'WorkEmail', size: 3, parentKey: 'BuyerClient_id' },
    { key: 'Notes', size: '', parentKey: 'BuyerClient_id' },
    { key: 'Employer', size: '', parentKey: 'BuyerClient_id' },
    { key: 'Occupation', size: '', parentKey: 'BuyerClient_id' },
  ],
  agency: [
    { key: 'brokerageName', size: 24, hideInList: true },
    { key: 'Address1', size: 12 },
    { key: 'Address2', size: 12 },
    { key: 'City', size: 12 },
    { key: 'ProvState', size: 6 },
    { key: 'ZipPostal', size: 6 },
    { key: 'Country', size: 12 },
    { key: 'Fax', size: '' },
    { key: 'WebSiteURL', size: '' },
    { key: 'Notes', size: '' },
  ],
  buyerClients: [
    { key: 'Address1', size: 12 },
    { key: 'Address2', size: 12 },
    { key: 'City', size: 12 },
    { key: 'ProvState', size: 6 },
    { key: 'ZipPostal', size: 6 },
    { key: 'Country', size: 6 },
    { key: 'HomePhone', size: '' },
    { key: 'WorkPhone', size: '' },
    { key: 'WorkEmail', size: '' },
    { key: 'ContactName', size: '' },
    { key: 'Employer', size: '' },
    { key: 'Occupation', size: '' },
    { key: 'Notes', size: '' },
  ],
};
