import { HomeFilled, MailFilled, SettingFilled } from '@ant-design/icons';
import CaseIcon from '../assets/images/custom-icons/CaseIcon';
import ProjectsIcon from '../assets/images/custom-icons/ProjectsIcon';
import CRMIcon from '../assets/images/custom-icons/CRMIcon';

export const protectedRouts = {
  brokers: {
    dashboard: {
      pageTitle: 'Dashboard',
      key: 'dashboard',
      icon: <HomeFilled />,
      pathname: '/dashboard',
      component: 'pages/dashboard-pages/dashboard.page',
    },
    messages: {
      pageTitle: 'Messages',
      key: 'messages',
      icon: <MailFilled />,
      pathname: '/messages',
      component: 'pages/dashboard-pages/brokers/messages.page',
    },
    allocation: {
      pageTitle: 'Allocations',
      key: 'allocation',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/allocations',
      component: 'pages/dashboard-pages/brokers/allocation-requests.page',
    },
    settings: {
      key: 'settings',
      pageTitle: 'Settings',
      icon: <SettingFilled />,
      pathname: '/settings',
      component: 'pages/dashboard-pages/brokers/profile.page',
      items: {
        profile: {
          subKey: 'settings',
          pageTitle: 'Profile',
          key: 'profile',
          pathname: '/profile',
          component: 'pages/dashboard-pages/brokers/profile.page',
        },
      },
    },
    projects: {
      pageTitle: 'Projects',
      key: 'projects',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/projects',
      component: 'pages/dashboard-pages/brokers/projects.page',
    },
    projectsSingle: {
      pageTitle: 'Projects',
      key: 'projects_single',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/projects/:projectId',
      hideInSidebar: true,
      component: 'pages/dashboard-pages/brokers/projects-single.page',
    },
    my_sales: {
      pageTitle: 'My sales',
      key: 'my_sales',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/my-sales',
      component: 'pages/dashboard-pages/brokers/my-sales.page',
    },
  },
  client: {
    dashboard: {
      pageTitle: 'Dashboard',
      key: 'dashboard',
      icon: <HomeFilled />,
      pathname: '/dashboard',
      component: 'pages/dashboard-pages/dashboard.page',
    },
    messages: {
      pageTitle: 'Messages',
      key: 'messages',
      icon: <MailFilled />,
      pathname: '/messages',
      component: 'pages/dashboard-pages/client/messages.page',
    },
    messagesChat: {
      pageTitle: 'Message Chat',
      key: 'message_chat',
      hideInSidebar: true,
      pathname: '/messages/:type',
      component: 'pages/dashboard-pages/client/message-chat.page',
    },
    purchases: {
      pageTitle: 'My purchases',
      key: 'purchases',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/my-purchases',
      component: 'pages/dashboard-pages/client/my-purchases.page',
    },
    settings: {
      key: 'settings',
      pageTitle: 'Settings',
      icon: <SettingFilled />,
      pathname: '/settings',
      component: 'pages/dashboard-pages/client/profile.page',
      items: {
        profile: {
          subKey: 'settings',
          pageTitle: 'Profile',
          key: 'profile',
          pathname: '/profile',
          component: 'pages/dashboard-pages/client/profile.page',
        },
      },
    },
    investment_opportunities: {
      pageTitle: 'Investment Opportunities',
      key: 'investment_opportunities',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/investment-opportunities',
      component: 'pages/dashboard-pages/client/investment-opportunities.page',
    },
    opportunitiesSingle: {
      pageTitle: 'Investment Opportunities',
      key: 'opportunities_single',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/investment-opportunities/:projectId',
      hideInSidebar: true,
      component: 'pages/dashboard-pages/client/opportunities-single.page',
    },
  },
  sale_office: {
    dashboard: {
      pageTitle: 'Dashboard',
      key: 'dashboard',
      icon: <HomeFilled />,
      pathname: '/dashboard',
      component: 'pages/dashboard-pages/dashboard.page',
    },
    messages: {
      pageTitle: 'Messages',
      key: 'messages',
      icon: <MailFilled />,
      pathname: '/messages',
      component: 'pages/dashboard-pages/sale-office/messages.page',
    },
    builderSetup: {
      pageTitle: 'Builder Setup',
      key: 'builder_setup',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/builder-setup',
      component: 'pages/dashboard-pages/sale-office/builder-setup.page',
    },
    projects: {
      key: 'projects',
      pageTitle: 'Projects',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/projects',
      component: 'pages/dashboard-pages/sale-office/project-setup.page',
      items: {
        projectSetup: {
          subKey: 'projects',
          pageTitle: 'Project Setup',
          key: 'project_setup',
          pathname: '/project-setup',
          component: 'pages/dashboard-pages/sale-office/project-setup.page',
        },
      },
    },
    projectsSingle: {
      pageTitle: 'Projects',
      key: 'projects_single',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/projects/:projectId',
      hideInSidebar: true,
      component: 'pages/dashboard-pages/brokers/projects-single.page',
    },
    allocations: {
      pageTitle: 'Allocations',
      key: 'allocations',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/allocations',
      component: 'pages/dashboard-pages/sale-office/allocations.page',
    },
    userManagement: {
      key: 'userManagement',
      pageTitle: 'User management',
      icon: <CaseIcon className='case_icon' />,
      pathname: '/user-management',
      component: 'pages/dashboard-pages/sale-office/purchaser-list.page',
      items: {
        purchaserList: {
          subKey: 'userManagement',
          pageTitle: 'Purchaser List',
          key: 'purchaserList',
          pathname: '/purchaser-list',
          component: 'pages/dashboard-pages/sale-office/purchaser-list.page',
        },
        brokerList: {
          subKey: 'userManagement',
          pageTitle: 'Broker List',
          key: 'brokerList',
          pathname: '/broker-list',
          component: 'pages/dashboard-pages/sale-office/broker-list.page',
        },
      },
    },
  },
  admin: {
    dashboard: {
      pageTitle: 'Dashboard',
      key: 'dashboard',
      icon: <HomeFilled />,
      pathname: '/dashboard',
      component: 'pages/dashboard-pages/admin/dashboard.page',
    },
    projectSettings: {
      key: 'projectSettings',
      pageTitle: 'Project Settings',
      icon: <ProjectsIcon />,
      pathname: '/project-settings',
      component: 'pages/dashboard-pages/admin/project-settings/project-setup.page',
      items: {
        projectSetup: {
          subKey: 'projectSettings',
          pageTitle: 'Project Setup',
          key: 'projectSetup',
          pathname: '/project-setup',
          component: 'pages/dashboard-pages/admin/project-settings/project-setup.page',
        },
        decorModelOptions: {
          subKey: 'projectSettings',
          pageTitle: 'Model Options',
          key: 'decorModelOptions',
          pathname: '/decor-model-options',
          component: 'pages/dashboard-pages/admin/project-settings/decor-model-options.page',
        },
        projectFinishes: {
          subKey: 'projectSettings',
          pageTitle: 'Project Finishes',
          key: 'projectFinishes',
          pathname: '/project-finishes',
          component: 'pages/dashboard-pages/admin/project-settings/project-finishes.page',
        },
        floorPremiums: {
          subKey: 'projectSettings',
          pageTitle: 'Floor Premiums',
          key: 'floorPremiums',
          pathname: '/floor-premiums',
          component: 'pages/dashboard-pages/admin/project-settings/floor-premiums.page',
        },
        modelsPlans: {
          subKey: 'projectSettings',
          pageTitle: 'Models & Plans',
          key: 'modelsPlans',
          pathname: '/models-plans',
          component: 'pages/dashboard-pages/admin/project-settings/models-plans.page',
        },
        unitsSuites: {
          subKey: 'projectSettings',
          pageTitle: 'Units & Suites',
          key: 'unitsSuites',
          pathname: '/units-suites',
          component: 'pages/dashboard-pages/admin/project-settings/units-suites.page',
        },
        projectParkingLocker: {
          subKey: 'projectSettings',
          pageTitle: 'Parking & Locker',
          key: 'projectParkingLocker',
          pathname: '/project-parking-locker',
          component: 'pages/dashboard-pages/admin/project-settings/project-parking-locker.page',
        },
        projectIncentives: {
          subKey: 'projectSettings',
          pageTitle: 'Project Incentives',
          key: 'projectIncentives',
          pathname: '/project-incentives',
          component: 'pages/dashboard-pages/admin/project-settings/project-incentives.page',
        },
        projectPremiums: {
          subKey: 'projectSettings',
          pageTitle: 'Project Premiums',
          key: 'projectPremiums',
          pathname: '/project-premiums',
          component: 'pages/dashboard-pages/admin/project-settings/project-premiums.page',
        },
        projectDeposits: {
          subKey: 'projectSettings',
          pageTitle: 'Project Deposits',
          key: 'projectDeposits',
          pathname: '/project-deposits',
          component: 'pages/dashboard-pages/admin/project-settings/project-deposits.page',
        },
      },
    },
    crm: {
      key: 'crm',
      pageTitle: 'CRM Accounts',
      icon: <CRMIcon className='case_icon' />,
      pathname: '/crm',
      component: 'pages/dashboard-pages/admin/crm/builder-clients.page',
      items: {
        builderClients: {
          subKey: 'crm',
          pageTitle: 'Builder Clients',
          key: 'builderClients',
          pathname: '/builder-clients',
          component: 'pages/dashboard-pages/admin/crm/builder-clients.page',
        },
        brokerAgencies: {
          subKey: 'crm',
          pageTitle: 'Broker Agencies',
          key: 'brokerAgencyList',
          pathname: '/broker-agencies',
          component: 'pages/dashboard-pages/admin/crm/broker-agencies.page',
        },
        CoBrokeAgents: {
          subKey: 'crm',
          pageTitle: 'Co-Broker Agents',
          key: 'CoBrokeAgents',
          pathname: '/co-broke-agents',
          component: 'pages/dashboard-pages/admin/crm/co-broke-agents.page',
        },
        leadsClients: {
          subKey: 'crm',
          pageTitle: 'Leads & Clients',
          key: 'leadsClients',
          pathname: '/leads-clients',
          component: 'pages/dashboard-pages/admin/crm/leads-clients.page',
        },
        purchasers: {
          subKey: 'crm',
          pageTitle: 'Purchasers',
          key: 'purchasers',
          pathname: '/purchasers',
          component: 'pages/dashboard-pages/admin/crm/purchasers.page',
        },
        professionals: {
          subKey: 'crm',
          pageTitle: 'Professionals',
          key: 'professionals',
          pathname: '/professionals',
          component: 'pages/dashboard-pages/admin/crm/professionals.page',
        },
      },
    },
    optionsLibrary: {
      key: 'optionsLibrary',
      pageTitle: 'Options Library',
      icon: <CaseIcon />,
      pathname: '/options-library',
      component: 'pages/dashboard-pages/admin/options-library/decor-categories.page',
      items: {
        decorCategories: {
          subKey: 'optionsLibrary',
          pageTitle: 'Decor Categories',
          key: 'decorCategories',
          pathname: '/decor-categories',
          component: 'pages/dashboard-pages/admin/options-library/decor-categories.page',
        },
        selectionGroups: {
          subKey: 'optionsLibrary',
          pageTitle: 'Selection Groups',
          key: 'selectionGroups',
          pathname: '/selection-groups',
          component: 'pages/dashboard-pages/admin/options-library/selection-groups.page',
        },
        supplierFinishes: {
          subKey: 'optionsLibrary',
          pageTitle: 'Supplier Finishes',
          key: 'supplierFinishes',
          pathname: '/supplier-finishes',
          component: 'pages/dashboard-pages/admin/options-library/supplier-finishes.page',
        },
        optionsMaster: {
          subKey: 'optionsLibrary',
          pageTitle: 'Decor Products',
          key: 'decorProducts',
          pathname: '/decor-products',
          component: 'pages/dashboard-pages/admin/options-library/decor-products.page',
        },
        parkingLocker: {
          subKey: 'optionsLibrary',
          pageTitle: 'Parking & Locker',
          key: 'parkingLocker',
          pathname: '/parking-locker',
          component: 'pages/dashboard-pages/admin/options-library/parking-locker.page',
        },
      },
    },
    systemMasters: {
      key: 'systemMasters',
      pageTitle: 'System Masters',
      icon: <CaseIcon />,
      pathname: '/system-masters',
      component: 'pages/dashboard-pages/admin/system-masters/floor-levels.page',
      items: {
        floorLevels: {
          subKey: 'systemMasters',
          pageTitle: 'Floor Levels',
          key: 'floorLevels',
          pathname: '/floor-levels',
          component: 'pages/dashboard-pages/admin/system-masters/floor-levels.page',
        },
        roomAreas: {
          subKey: 'systemMasters',
          pageTitle: 'Room Areas',
          key: 'roomAreas',
          pathname: '/room-areas',
          component: 'pages/dashboard-pages/admin/system-masters/room-areas.page',
        },
        premiums: {
          subKey: 'systemMasters',
          pageTitle: 'Premiums',
          key: 'premiums',
          pathname: '/premiums',
          component: 'pages/dashboard-pages/admin/system-masters/premiums.page',
        },
        incentives: {
          subKey: 'systemMasters',
          pageTitle: 'Incentives',
          key: 'incentives',
          pathname: '/incentives',
          component: 'pages/dashboard-pages/admin/system-masters/incentives.page',
        },
        documents: {
          subKey: 'systemMasters',
          pageTitle: 'Documents',
          key: 'documents',
          pathname: '/documents',
          component: 'pages/dashboard-pages/admin/system-masters/documents.page',
        },
        depositPlans: {
          subKey: 'systemMasters',
          pageTitle: 'Deposit Plans',
          key: 'depositPlans',
          pathname: '/deposit-plans',
          component: 'pages/dashboard-pages/admin/system-masters/deposit-plans.page',
        },
      },
    },
  },
};

const routes = {
  notFound: {
    pathname: '/404',
    key: 'not_found',
    pageTitle: '404',
  },
  home: {
    pathname: '/',
    key: 'home',
    component: 'pages/home.page',
    pageTitle: 'Home',
  },
  signIn: {
    pathname: '/sign-in',
    key: 'sign-in',
    component: 'pages/auth-pages/auth-tabs.page',
    pageTitle: 'Sign In',
  },
  signUp: {
    pathname: '/sign-up',
    key: 'sign-up',
    component: 'pages/auth-pages/auth-tabs.page',
    pageTitle: 'Sign Up',
  },
  thank: {
    pathname: '/thank-you',
    key: 'thank-you',
    component: 'pages/auth-pages/thank-you.page',
    pageTitle: 'Thank You',
  },
};

export default routes;
